version : '3'

services:
    lb:
        image: haproxy
        ports:
            - "8087:8080"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    adminservice1:
        image: adminservice
        environment:
            - APPID=1111
    adminservice2:
        image: adminservice
        environment:
            - APPID=2222
    adminservice3:
        image: adminservice
        environment:
            - APPID=3333
    adminservice4:
        image: adminservice
        environment:
            - APPID=4444